### ISSUE TITLE
[Enhancement]: Suggest Using MkDocs or TypeScript Equivalent to Render Our Docs into a GitHub Page

### ISSUE THREAD

**Issue by JSv4** [Open-Cap-Table-Coalition/Open-Cap-Format-OCF#281]
### Description of Enhancement :

I've recently started using [MkDocs](https://github.com/mkdocs/mkdocs) to render project documentation for some other projects I'm working on. It's a powerful but still light-weight solution that takes valid Markdown and converts it into very nice html, complete with nav and a much nicer look and feel. I think the [Python Hatch Project Docs](https://hatch.pypa.io/latest/) provide a great look at what's possible with the tool. 

The best part is you can [deploy the resulting html page instantly to GitHub pages](https://www.mkdocs.org/user-guide/deploying-your-docs/). I believe you could do all of this with an action. 

Obviously this would introduce some further deployment complexity (and Python dependencies), but I think we should consider this (or something like it) to further package and serve the docs in the near future. If anyone is aware of something similar written in TypeScript, I'm all ears. 

### Why is this Needed?

Our Markdown docs are fantastic from a content perspective. They have a lot of content and are comprehensive. I think they're getting a bit unwieldy, however, and GitHub markdown isn't the prettiest. Searching them is hard. Browsing the README can be overwhelming, I'd imagine. 

Using a tool like this lets us leverage our existing Markdown docs and toolchain while adding substantial improvements in usability. 

### Anything else we need to know?

Check out the [MkDocs project page](https://github.com/mkdocs/mkdocs) and the example docs from the [Hatch project](https://hatch.pypa.io/latest/).

**Comment by naveedn** [comment]
Hey, I took a crack at this last night, and I'd like to report some findings:

**Investigation:**
- I read through [Markdoc](https://markdoc.dev/), Stripe's developer API doc generator via Markdown, and promptly decided it was too complex for our use case -- it provides custom options to parse the AST, and extends Markdown API with annotations, which we wouldn't be able to take advantage of because we have our markdown files from jsonschema. 
- I tried [slatedocs](https://github.com/slatedocs/slate), and while I was able to get it working with a docker container, it relies on node, ruby, and a few other dependencies. Ultimately, it was going to be burdensome to maintain that toolchain alongside the repo code, not to mention it requires the markdown files in a specific file format and structure to properly parse the page. Also, the search functionality was lacking, so I started looking at another alternative.
- I tried [mkdocs](https://www.mkdocs.org/getting-started/), and honestly, it was such a delight to use! It took about 30 seconds to set up, and after looking at Hatch's documentation site, I realize that they borrowed the [material theme](https://squidfunk.github.io/mkdocs-material/), which provides A LOT out of the box. We get an advanced search, and the plugins available allow for a lot of customization. I added [awesome-pages](https://github.com/lukasgeiter/mkdocs-awesome-pages-plugin) to give more flexibility in our navigation structure. 

**Results**
- https://naveedn.github.io/Open-Cap-Format-OCF/ is the site I was able to push up with MkDocs
- Created a Draft PR with the code changes I made, soliciting feedback and would like to figure out if this is directionally where we want to go.  


**TODO:**
- verify that github actions work as expected (untested)
- Add logo, favicon, and other assets to make the page properly render
- determine why the navigation left sidebar does not also show schema
- Add more / better documentation (I copied the readme into the docs root, but we could iterate on this)
