### ISSUE TITLE
[Bug]: README.md gets generated in a different order on Windows

### ISSUE THREAD

**Issue by xudiera** [Open-Cap-Table-Coalition/Open-Cap-Format-OCF#291]
### Current Behavior:

If you run `npm run generate-docs` on a Windows machine the README.md file gets generated in a different order. See below:

![image](https://user-images.githubusercontent.com/3137781/196538724-e8dab92f-c2c4-4ecc-a5cf-813b1abf46b2.png)

Notice how the section **Enum - Object Type** it is now above section **Enum - OCF Version Type**

### Expected Behavior:

Documents generation should work the same on Windows, macOS, and Linux.

### Steps to Reproduce:

Run the doc generator on Windows.

### Environment:

- OS: Windows 10
- Node: 16.13.1
- npm: 8.1.2

**Comment by JSv4** [comment]
@xudiera, FYI, most likely I think we're going to close this. As part of the work I'm doing with @naveedn on serving our documentation via MkDocs, I realized we no longer need to generate an index because a) MkDocs does it and b) MkDocs' version looks way better and renders the indices we are generating poorly (they look like crap without some formatting updates). Rather than fix this bug (which doesn't affect anything substantively), I'd propose we just drop generating our own index, in which case this is irrelevant.

**Comment by JSv4** [comment]
Per the TWG call 12/6/22, we are not going to generate the index ourselves anymore. We're relying on MkDocs to serve the docs and generate an index.
