### ISSUE TITLE
[Enhancement]: Look Into and Remove Any Circular References

### ISSUE THREAD

**Issue by JSv4** [Open-Cap-Table-Coalition/Open-Cap-Format-OCF#405]
### Description of Enhancement :

As noted in TWG discussion re: #378, there are circular references in a few places in the schema. This is causing some difficulty with pyOCF and is probably unintentional. Find and remove. 

### Why is this Needed?

Probably an unintentional design pattern and not one we want to use. If it makes third-party tooling easier, we should remove this.

**Comment by JSv4** [comment]
@regebro, are you interested in taking this one?

**Comment by regebro** [comment]
Absolutely

**Comment by JSv4** [comment]
Awesome. Assigned! I'll get you on the TWG call invites too.

**Comment by pjohnmeyer** [comment]
@regebro Any updates on this?

**Comment by regebro** [comment]
No, I need to discuss it, but can't make today's meeting.

**Comment by pjohnmeyer** [comment]
Can you pose your questions / thoughts here async?

**Comment by regebro** [comment]
I can try, it's very vague. :-)

Basically, I have confirmed that there are no strict circular references. (I tried extending ajv to check for that as well, but ajv didn't seem very extendable, except for adding keywords).

The circular import problem we got in Python is due to primitives having types as properties, and types also being composed of primitives. And this doesn't cause a problem per se, it was just with a couple of types/primitives we had that problem.

And I don't really see a way of changing that mutual dependency. In the PR I did I got rid of the problem just for the cases that caused a problem, but there is nothing there to prevent it from happening again in other cases.

So the question / thought I have is to a large extent whether we should bother to do anything about this, or if we even can.
