### ISSUE TITLE
[Bug]: Committing with no changes to the repo results in changes from the pre-commit hook

### ISSUE THREAD

**Issue by osis** [Open-Cap-Table-Coalition/Open-Cap-Format-OCF#476]
### Current Behavior:

When I check out the latest master, do no changes, and try to commit do a commit there are a number of changes that are generated.

### Expected Behavior:

The pre-commit hook shouldn't generate changes that differ from what's in the main branch.

### Steps to Reproduce:

1. Check out `main`
2. Generate a commit

### Environment:

- OS: Ubuntu 20.04
- Node: 18.19.0
- npm: 10.2.3

### Anything else we need to know?

The two types of diffs that show up that are not getting linted by `lint-staged` are...
```diff
-  "enum": ["DAILY", "MONTHLY", "QUARTERLY", "SEMI_ANNUAL", "ANNUAL"],
+  "enum": [
+    "DAILY",
+    "MONTHLY",
+    "QUARTERLY",
+    "SEMI_ANNUAL",
+    "ANNUAL"
+  ],
```

```diff
-}
+}
\ No newline at end of file
```

Full diff of changes can be seen in #474

**Comment by pjohnmeyer** [comment]
@osis I was unable to reproduce this with the version of Node in the .nvmrc file. When you say "generate a commit" -- is it an empty commit, or *any* commit?

**Comment by osis** [comment]
@pjohnmeyer it's an empty commit.

**Comment by pjohnmeyer** [comment]
That's odd because `lint-staged` doesn't normally allow an empty commit. To make sure it wasn't anything weird about my environment I made a fresh clone and went through the steps:

* gh repo clone Open-Cap-Table-Coalition/Open-Cap-Format-OCF
* cd Open-Cap-Format-OCF/
* nvm use
* npm install
* git commit --allow-empty -m 'Testing #476'

This did not generate a commit at all, much less commit a modified file.

I wouldn't expect your Node or npm versions to cause this behavior, but please try with the current toolchain and see if it makes a difference.

Output:

<pre><font color="#4E9A06"><b>plj1@pop-os</b></font>:<font color="#3465A4"><b>~/code/oct</b></font>$ gh repo clone Open-Cap-Table-Coalition/Open-Cap-Format-OCF
Cloning into &apos;Open-Cap-Format-OCF&apos;...
remote: Enumerating objects: 18798, done.
remote: Counting objects: 100% (1589/1589), done.
remote: Compressing objects: 100% (426/426), done.
remote: Total 18798 (delta 1099), reused 1339 (delta 955), pack-reused 17209
Receiving objects: 100% (18798/18798), 7.86 MiB | 4.30 MiB/s, done.
Resolving deltas: 100% (14949/14949), done.
<font color="#4E9A06"><b>plj1@pop-os</b></font>:<font color="#3465A4"><b>~/code/oct</b></font>$ cd Open-Cap-Format-OCF/
<font color="#4E9A06"><b>plj1@pop-os</b></font>:<font color="#3465A4"><b>~/code/oct/Open-Cap-Format-OCF</b></font>$ nvm use
Found &apos;/home/plj1/code/oct/Open-Cap-Format-OCF/.nvmrc&apos; with version &lt;v18.16.0&gt;
Now using node v18.16.0 (npm v9.5.1)
<font color="#4E9A06"><b>plj1@pop-os</b></font>:<font color="#3465A4"><b>~/code/oct/Open-Cap-Format-OCF</b></font>$ npm install
<span style="background-color:#333333"><font color="#D3D7CF">npm</font></span> <span style="background-color:#C4A000"><font color="#333333">WARN</font></span> <font color="#75507B">deprecated</font> stringify-package@1.0.1: This module is not used anymore, and has been replaced by @npmcli/package-json
<span style="background-color:#333333"><font color="#D3D7CF">npm</font></span> <span style="background-color:#C4A000"><font color="#333333">WARN</font></span> <font color="#75507B">deprecated</font> source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
<span style="background-color:#333333"><font color="#D3D7CF">npm</font></span> <span style="background-color:#C4A000"><font color="#333333">WARN</font></span> <font color="#75507B">deprecated</font> urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
<span style="background-color:#333333"><font color="#D3D7CF">npm</font></span> <span style="background-color:#C4A000"><font color="#333333">WARN</font></span> <font color="#75507B">deprecated</font> resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
<span style="background-color:#333333"><font color="#D3D7CF">npm</font></span> <span style="background-color:#C4A000"><font color="#333333">WARN</font></span> <font color="#75507B">deprecated</font> source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
<span style="background-color:#333333"><font color="#D3D7CF">npm</font></span> <span style="background-color:#C4A000"><font color="#333333">WARN</font></span> <font color="#75507B">deprecated</font> w3c-hr-time@1.0.2: Use your platform&apos;s native performance.now() and performance.timeOrigin.
<span style="background-color:#333333"><font color="#D3D7CF">npm</font></span> <span style="background-color:#C4A000"><font color="#333333">WARN</font></span> <font color="#75507B">deprecated</font> sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead

&gt; prepare
&gt; husky install

husky - Git hooks installed

added 1156 packages, and audited 1157 packages in 8s

143 packages are looking for funding
  run `npm fund` for details

<font color="#CC0000"><b>16</b></font> vulnerabilities (6 <font color="#C4A000"><b>moderate</b></font>, 8 <font color="#CC0000"><b>high</b></font>, 2 <font color="#75507B"><b>critical</b></font>)

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
<font color="#4E9A06"><b>plj1@pop-os</b></font>:<font color="#3465A4"><b>~/code/oct/Open-Cap-Format-OCF</b></font>$ git commit --allow-empty -m &apos;Testing #476&apos;

&gt; schema:enforce-copyright-notices
&gt; node --loader ts-node/esm --no-warnings --experimental-json-modules ./utils/schema-utils/EnforceCopyrightNotices.ts check-notices -fvart --tag main

ENFORCE COPYRIGHT NOTICES ----------------------
	force_overwrite: true 
	add_missing_comments: true 
	tag: main 
	test: true

Traverse schema dir for schema paths...

~~~~~~~~~~~~~~~~~~~~~~~~~~~ ... SNIP ... ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

https://raw.githubusercontent.com/Open-Cap-Table-Coalition/Open-Cap-Format-OCF/main/schema/enums/ValuationType.schema.json
https://raw.githubusercontent.com/Open-Cap-Table-Coalition/Open-Cap-Format-OCF/main/schema/enums/VestingDayOfMonth.schema.json
https://raw.githubusercontent.com/Open-Cap-Table-Coalition/Open-Cap-Format-OCF/main/schema/enums/VestingTriggerType.schema.json
Finished. /home/plj1/code/oct/Open-Cap-Format-OCF
<font color="#4E9A06">✔</font> Preparing lint-staged...
<font color="#4E9A06">✔</font> Running tasks for staged files...
<font color="#CC0000">✖</font> Prevented an empty git commit!
<font color="#4E9A06">✔</font> Reverting to original state because of errors...
<font color="#4E9A06">✔</font> Cleaning up temporary files...

  <font color="#C4A000">⚠ lint-staged prevented an empty git commit.</font>
<font color="#C4A000">  Use the --allow-empty option to continue, or check your task configuration</font>

husky - pre-commit hook exited with code 1 (error)
</pre>

**Comment by JSv4** [comment]
So @pjohnmeyer, agreed that the empty commits should be blocked. That said, I think we discussed seeing similar behavior in the past where the linter was making these changes sometimes. We never did track it down. @osis, have you seen other situations where the changes are created except an empty commit?
