### ISSUE TITLE
[Question]: Future support for LLCs (membership interests)?

### ISSUE THREAD

**Issue by mrosendin** [Open-Cap-Table-Coalition/Open-Cap-Format-OCF#502]
### Question:

The current OCF for v1.0 targets compatibility for stock corporations. I was wondering if it has been brought up yet or planned for future versions of OCF to include support for membership interests or unit interests in LLCs. A common data format for managing equity in LLCs has major applications for SPVs, alternative investment funds, and similar structures.

**Comment by JSv4** [comment]
Things we could start with:

- Model economic ownership %s / units instead of stock. 
   - Economics can vary tremendously
   - Pro forma would have to change a lot potentially.
   - Flagging the type at the Company level  
- To extent we're just tracking the types of interest and count of them
    - We need to understand the data model a little better and what needs to be tracked
    - How much of the DE C Corp model can we use? 

TWG to chime in here on what they've done in the past.

**Comment by Sumukh** [comment]
* LLC Membership Classes map to Share Classes 
  * Interests in a membership class maps to instruments under a share class. 
  * We will need some kind of primitive for tracking distributions (to get to capital account balances)

**Comment by JSv4** [comment]
I'm closing this for now. If we do a project to add LLC support, we can revisit.

**Comment by victormimo** [comment]
Do we have any interest in opening this topic back up? I'm sure every participant here has been asked by a customer. @JSv4 let me know how contributions can take place, if I (fairmint.com) can take a stab at it and request a review.
